### ISSUE TITLE
Just FYI - This package was responsible for...

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#115]
https://github.com/JuliaGraphs/LightGraphs.jl/pull/687

Thank you :)

**Comment by davidanthoff** [comment]
Very cool, @ZacLN just has done great work on all of this. We should probably advertise this feature more widely, when I announced the last release of the extension on discourse I kind of messed up by not mentioning this at all in the initial post, mainly because I hadn't understood that this feature was actually there ;)

**Comment by ZacLN** [comment]
Nice! Out of interest how many things did it get wrong (excluding the transpose)

**Comment by sbromberger** [comment]
a couple of glitches that required me to add and then remove a newline. I couldn't find a consistent pattern so didn't report it. Every other white space complaint was legitimate. It worked really well and it resulted in changes to pretty much every single file.
