### ISSUE TITLE
Lint all documents upon receiving `initialize` method not `initialized` notification.

### ISSUE THREAD

**Issue by randy3k** [JuliaEditorSupport/LanguageServer.jl#178]
Right now, LS starts linting all files after the `initialized` notification. However, in this state, the editor already thinks that LS is fully operational and will keep sending notifications like `textDocument/didOpen` or `textDocument/didChange`. I reckon that these lintings should be actually done upon receiving `initialize` method, but until the `initialized` notification.

The `initialized` notification, if I understand correctly, should only perform something quick.

**Comment by davidanthoff** [comment]
Might be a good idea to see how other language servers implement this, or ask over in the MS repo. It sounds plausible to me, but it would be good to check and make sure we are in line with the official guidelines. @dbaeumer any view on this?

**Comment by ZacLN** [comment]
I think moving this (and thus preventing `didChange` notifications) will mean that we get a mis-match between document versions in the editor and on the server if any edits are made during the startup period

**Comment by randy3k** [comment]
well, but it may be frustrating to see the message "Language server initialized", but noting is operational (yet).

**Comment by davidanthoff** [comment]
I think we will only be able to solve this properly once there is better threading support in base. At the end of the day we would want to have one thread process incoming messages, and another (background) thread parsing and linting. That would keep the message processing thread responsive at all times. It might not always be able to return a useful return message (because e.g. the parsing thread isn't finished), but it would not block things. The only way to do this today would be to use more julia processes, and I think that is worse: it is complicated, uses too many resources, and then we'll have to rip it all out again once there is better threading in base.

At the same time, things should get better once we move at least the loading user packages into a separate process. That is planned because we would want to have that in a separate process even if there was better threading in base.

**Comment by ZacLN** [comment]
This is just relating to the naming of lsp notification names though. The `initialize` period is - as far as I can tell - intended for exactly this sort of thing. The more pertinant issue is general startup time which is entirely down to improving the precompilation of CSTParser/ linting in LanguageServer
