### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#34]
I see two paths: 1) we wait until @ZacLN's JuliaParser rewrite enables code formatting or 2) someone tries to use https://github.com/KristofferC/Tokenize.jl to add something in the meantime.

My guess is that neither @ZacLN nor I will get to 2) anytime soon, but if someone wants to contribute something along those lines, let us know here and we'll help you get started!

**Comment by ZacLN** [comment]
I've started on this and don't think it's quite feasible to build it onto of JuliaParser, I just don't think its suitable to force the use of  `Expr` as a descriptor of concrete code structure. I'm going to have a go at rewriting a parser from the ground up in a more Julian fashion (as apposed to the direct transpose of the scheme parser) using Tokenize.

I'll start off with one that handles a small subset of  the syntax specification but that implements all the features that we want. From this point, if it's speedy enough it should be straightforward to extend it to handle all cases in a modular fashion.

I.e. to start
- parse function calls
- parse assignment operators
- parse block declarations

then:
- handle chained binary ops
- handle reserved word (type declarations, method declarations, control flows, etc...)
- handle type specifications
- handle matrix,vector, range, generator declarations,  
etc...

One of my aims is to make the parser much less opaque so it should be easier for those interested to contribute (and would make maintenance less dependent on one/a few people)

**Comment by davidanthoff** [comment]
Cool! One thing that would be great is if we could get incremental parsing a la Roslyn. I think the key to that is that the data strutures that are returned from the tokenizer already don't have line/column or position info, but instead only have a ``length`` field, so that they can be reused, even if that particular piece of code ends up being moved around in the text document.

**Comment by ZacLN** [comment]
I spent a few hours on this yesterday and so far redoing the parser doesn't seem _too_ onerous a task. I've got no access to Visual Studio/Roslyn yet so what would be helpful is if you could give me an idea of the sorts of features we'd want to provide. 

FYI my initial approach is [here](https://github.com/ZacLN/Parser.jl)

**Comment by novatena2015** [comment]
Your initial approach seems very nice. But I don't see how you are dealing with comment.

I've tested with following oneliner function, the test failed.

`    f(x#=commen=#) = x
`

**Comment by ZacLN** [comment]
Lemme push an update but as I said above, it's missing loads of syntactical features

**Comment by ZacLN** [comment]
OK, I've been doing this bit by bit over the last week and I think I've got enough of the parser working to add the relevant features to it.

[This](https://github.com/ZacLN/Parser.jl/tree/expr-format) is the relevant branch which handles:
- Operators (no dot ops)
- keyword blocks
- macros
- function calls

 ### Formatting
I've added an example of how it could return formatting tips as it parses: 
- It expects a single space following a coma except when in curly brackets
- It expects spaces before and after an assignment operator.
Other things like correct the indents on keyword blocks should be fairly straightforward.

### Re-factoring 
There's a simple tracker that notes the location of all occurrences of unique identifiers, this should easy to extended to track function calls and slightly harder to distinguish between names referring to distinct objects. In addition we will be able track variable types as we parse.

### Round-trippability 
All symbols keep track of trailing whitespace/comments. This may have to be changed to store leading and lagging whitespace in some situations so that we can have full knowledge of punctuation and positioning. At the moment positions are stored as start and stop but this is mainly for debugging as I write it and will be eventually stored simply as an offset. 


### Performance
Unoptimized this runs about 3-4x as fast as the scheme parser on my machine while allocating 6-7 times as much memory so there's lots of room to add fairly complex analytical computations without worrying about over burdening the system.

**Comment by davidanthoff** [comment]
Wow, very cool!

**Comment by ZacLN** [comment]
#48
